# Copyright (C) 2020 Christian Berger
# Copyright (C) 2022  Björnborg Nguyen
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: "3.6"

services:
    rpicamv2:
        container_name: rpicamv2
        image: registry.opendlv.org/bjornborg/opendlv-device-camera-rpicamv2:latest
        ipc: host
        network_mode: host
        privileged: true
        environment:
        - DISPLAY=${DISPLAY}
        volumes:
        - /sys:/sys:rw
        - /dev:/dev:rw
        - /run/udev:/run/udev:rw
        - /tmp:/tmp
        - /home/pi/.Xauthority:/root/.Xauthority
        command: "--mode 3280:2464:12:P --width 1920 --height 1080 --shutter 10000 --gain 4.0 --exposure sport --awb indoor --denoise cdn_fast #--verbose"

    kiwi-view:
        container_name: kiwi-view
        image: registry.opendlv.org/bjornborg/opendlv-ui-vehicleview:v0.0.67
        restart: always
        network_mode: "host"
        volumes:
        - /home/pi/recordings:/opt/vehicle-view/recordings
        - /var/run/docker.sock:/var/run/docker.sock
        environment:
        - OD4SESSION_CID=${CID}
        - OPENDLV_VEHICLE_VIEW_PLATFORM=Kiwi 

