# Copyright (C) 2020 Christian Berger
# Copyright (C) 2020  Björnborg Nguyen
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: "3.6"

services:
    device-camera-rpi:
        container_name: device-camera-rpi
        image: chalmersrevere/opendlv-device-camera-rpi-armhf:v0.0.6
        restart: always
        ipc: "host"
        privileged: true
        volumes:
        - /tmp:/tmp
        command: "--name.i420=img.i420 --name.argb=img.argb --width=${IMGWIDTH} --height=${IMGHEIGHT} --freq=20"
    kiwi-view:
        container_name: kiwi-view
        image: chalmersrevere/opendlv-vehicle-view-multi:v0.0.60
        restart: always
        network_mode: "host"
        volumes:
        - /home/pi/recordings:/opt/vehicle-view/recordings
        - /var/run/docker.sock:/var/run/docker.sock
#         temp fix
        - /root/opendlv-standard-message-set-v0.9.10.odvd:/opt/vehicle-view/opendlv-standard-message-set-v0.9.9.odvd
        environment:
        - OD4SESSION_CID=${CID}
        - OPENDLV_VEHICLE_VIEW_PLATFORM=Kiwi 

#       This encoder should not be enabled.
#     encoder: 
#         container_name: encoder 
#         depends_on:
#         - device-camera-rpi
#         image: chalmersrevere/opendlv-video-x264-encoder-armhf:v0.0.5
#         restart: always
#         network_mode: "host"
#         ipc: "host"
#         volumes:
#         - /tmp:/tmp
#         command: "--cid=${CID} --name=img.i420 --width=${IMGWIDTH} --height=${IMGHEIGHT}"
        
#         Recorder
        
#     video-x264-recorder-armhf:
#         image: chrberger/opendlv-video-x264-recorder:v0.0.4
#         restart: always
#         depends_on:
#         - device-camera-rpi
#         network_mode: "host"
#         ipc: "host"
#         working_dir: /recordings
#         volumes:
#         - /tmp:/tmp
#         - /home/pi/recordings:/recordings
#         command: "--cid=${CID} --name=img.i420 --width=${IMGWIDTH} --height=${IMGHEIGHT} --recsuffix=video-all"

        
#         This is probably not working. Need to fix this
#     encoder:
#         container_name: encoder
#         image: bjornborg/omx-encoder:latest
#         privileged: true
#         restart: always
#         network_mode: "host"
#         ipc: "host"
#         depends_on:
#         - device-camera-rpi
#         volumes:
#         - /tmp:/tmp
#         command: "--cid=${CID} --name=img.i420 --width=${IMGWIDTH} --height=${IMGHEIGHT}"
