# Copyright (C) 2018  Björnborg Nguyen
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: "3.6"

services:
    device-camera-rpi:
        container_name: device-camera-rpi
        image: chalmersrevere/opendlv-device-camera-rpi-armhf:v0.0.6
        restart: always
        ipc: "host"
        privileged: true
        volumes:
        - /tmp:/tmp
        command: "--name.i420=img.i420 --name.argb=img.argb --width=640 --height=480 --freq=20"


    encoder:
        container_name: encoder 
        depends_on:
        - device-camera-rpi
        image: chalmersrevere/opendlv-video-x264-encoder-armhf:v0.0.5
        restart: always
        network_mode: "host"
        ipc: "host"
        volumes:
        - /tmp:/tmp
        command: "--cid=${CID} --name=img.i420 --width=640 --height=480"

    kiwi-view:
        container_name: kiwi-view
        image: chalmersrevere/opendlv-vehicle-view-multi:v0.0.60
        restart: always
        network_mode: "host"
        volumes:
        - /home/pi/recordings:/opt/vehicle-view/recordings
        - /var/run/docker.sock:/var/run/docker.sock
#         temp fix
        - /root/opendlv-standard-message-set-v0.9.10.odvd:/opt/vehicle-view/opendlv-standard-message-set-v0.9.9.odvd
        environment:
        - OD4SESSION_CID=${CID}
        - OPENDLV_VEHICLE_VIEW_PLATFORM=Kiwi 
        ports:
        - "8081:8081"
